"""empty message

Revision ID: 04791824e482
Revises: 
Create Date: 2024-07-10 15:55:53.823315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04791824e482'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morador')
    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('email_sindico')

    op.drop_table('condominio')
    op.drop_table('veiculo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ano', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modelo', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('placa', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cor', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('condominio',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cep', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cidade', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('endereco', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('numero', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('celular', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('telefone', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nome_sindico', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('telefone_sindico', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_sindico', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.create_index('email_sindico', ['email_sindico'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('morador',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sobrenome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('cpf', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('celular', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('telefone', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
