"""Alteração de atributos unicos

Revision ID: 2966abdc1316
Revises: 72333f5018a5
Create Date: 2024-08-23 11:03:28.535268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2966abdc1316'
down_revision = '72333f5018a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morador')
    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['celular'])
        batch_op.create_unique_constraint(None, ['telefone'])
        batch_op.create_unique_constraint(None, ['nome'])

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['placa'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('morador',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sobrenome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('cpf', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('celular', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('telefone', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
