"""Atualizando tabela

Revision ID: 72333f5018a5
Revises: 04791824e482
Create Date: 2024-07-10 16:23:06.524353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72333f5018a5'
down_revision = '04791824e482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cep', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.String(length=35), nullable=False),
    sa.Column('endereco', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('celular', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nome_sindico', sa.String(length=50), nullable=False),
    sa.Column('telefone_sindico', sa.Integer(), nullable=False),
    sa.Column('email_sindico', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_sindico')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=20), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculo')
    op.drop_table('condominio')
    # ### end Alembic commands ###
